# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Delete

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run action against"
        type: environment
        required: false
jobs:
  delete:
    permissions:
      actions: read
      contents: read
      deployments: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Deploy deletion from Cloudflare Pages"
        uses: andykenward/github-actions-cloudflare-pages/delete@1465d3fcd395b60fc734b2d397699a3ff3f4b834 #v3.3.2
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
